"""empty message

Revision ID: 7507dec88108
Revises: 799181084290
Create Date: 2022-05-14 18:23:51.252103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7507dec88108'
down_revision = '799181084290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pp_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('connector_type_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connector_type_id'], ['connector_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(None, 'containers', type_='foreignkey')
    op.create_foreign_key(None, 'containers', 'container_types', ['cont_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'containers', type_='foreignkey')
    op.create_foreign_key(None, 'containers', 'connector_types', ['cont_type_id'], ['id'])
    op.drop_table('connectors')
    op.drop_table('pp_types')
    # ### end Alembic commands ###
