"""Add cables (with parrents)

Revision ID: cbd3029cf145
Revises: 802648198f5d
Create Date: 2022-05-17 12:08:11.198399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbd3029cf145'
down_revision = '802648198f5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('port_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cable_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('connector_a_id', sa.Integer(), nullable=False),
    sa.Column('connector_b_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connector_a_id'], ['connectors.id'], ),
    sa.ForeignKeyConstraint(['connector_b_id'], ['connectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pp_sides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_line_side', sa.Boolean(), nullable=True),
    sa.Column('patch_panel_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patch_panel_id'], ['patch_panels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('port_type_id', sa.Integer(), nullable=False),
    sa.Column('pp_side_id', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['port_type_id'], ['port_types.id'], ),
    sa.ForeignKeyConstraint(['pp_side_id'], ['pp_sides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('port_a_id', sa.Integer(), nullable=False),
    sa.Column('port_b_id', sa.Integer(), nullable=False),
    sa.Column('cable_type_id', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cable_type_id'], ['cable_types.id'], ),
    sa.ForeignKeyConstraint(['port_a_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['port_b_id'], ['ports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('patch_panels', sa.Column('creation_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patch_panels', 'creation_date')
    op.drop_table('cables')
    op.drop_table('ports')
    op.drop_table('pp_sides')
    op.drop_table('cable_types')
    op.drop_table('port_types')
    # ### end Alembic commands ###
